command:
  - python3
  - ${program}
  - ${args_no_hyphens}
entity: amacrutherford
method: grid
parameters:
  ANNEAL_LR:
    values:
      - true
  CLIP_EPS:
    values:
      - 0.05
      - 0.1
      - 0.2
  ENT_COEF:
    values:
      - 0.0
      - 0.01
      - 0.1
  GAE_LAMBDA:
    values:
      - 0.95
  GAMMA:
    values:
      - 0.99
  LR:
    values:
      - 0.004
      - 0.0005
  MAX_GRAD_NORM:
    values:
      - 0.25
      - 0.5
  NUM_ENVS:
    values:
      - 64
      - 128
      - 256
      - 512
  NUM_MINIBATCHES:
    values:
      - 2
      - 4
      - 16
  NUM_STEPS:
    values:
      - 128
  SEED:
    values:
      - 0
  TOTAL_TIMESTEPS:
    values:
      - 5e6
  UPDATE_EPOCHS:
    values:
      - 2
      - 4
      - 16
  VF_COEF:
    values:
      - 0.5
program: baselines/IPPO/ippo_rnn_mpe.py
project: mpe-rnn-sweep