command:
  - python3
  - ${program}
  - ${args_no_hyphens}
  - +env=smax 
  - +alg=qmix_smax
entity: 
method: grid
parameters:
  SEED:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12 
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19

  env.MAP_NAME:
    values:
      - smacv2_20_units
      - 27m_vs_30m
  
program: baselines/QLearning/vdn.py
project: smax-seed-sweep